apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Cert-Manager
#- ../manifests-1.3-branch/common/cert-manager/cert-manager-kube-system-resources/base
#- ../manifests-1.3-branch/common/cert-manager/cert-manager-crds/base
#- ../manifests-1.3-branch/common/cert-manager/cert-manager/overlays/self-signed
- ../manifests-1.3-branch/common/cert-manager/cert-manager/base
- ../manifests-1.3-branch/common/cert-manager/kubeflow-issuer/base

# Istio
#- istio
- ../manifests-1.3-branch/common/istio-1-9/istio-crds/base
- ../manifests-1.3-branch/common/istio-1-9/istio-namespace/base
- ../manifests-1.3-branch/common/istio-1-9/istio-install/base
- ../manifests-1.3-branch/common/istio-1-9/cluster-local-gateway/base


# OIDC Authservice
- ../manifests-1.3-branch/common/oidc-authservice/base


# Dex
- ../manifests-1.3-branch/common/dex/overlays/istio

# KNative
- ../manifests-1.3-branch/common/knative/knative-serving/base

#- ../manifests-1.3-branch/common/knative/knative-serving-install/base

- ../manifests-1.3-branch/common/knative/knative-eventing/base

#- ../manifests-1.3-branch/common/knative/knative-eventing-install/base


# Kubeflow namespace
- ../manifests-1.3-branch/common/kubeflow-namespace/base

# Kubeflow Roles
- ../manifests-1.3-branch/common/kubeflow-roles/base

# Kubeflow Istio Resources
- ../manifests-1.3-branch/common/istio-1-9/kubeflow-istio-resources/base

# Kubeflow Pipelines
- ../manifests-1.3-branch/apps/pipeline/upstream/env/platform-agnostic-multi-user
# ../manifests-1.3-branch/apps/pipeline/upstream/env/aws
# KFServing
- ../manifests-1.3-branch/apps/kfserving/upstream/overlays/kubeflow

# Central Dashboard
- ../manifests-1.3-branch/apps/centraldashboard/upstream/overlays/istio

# Admission Webhook
- ../manifests-1.3-branch/apps/admission-webhook/upstream/overlays/cert-manager

# Notebook Controller
- ../manifests-1.3-branch/apps/jupyter/jupyter-web-app/upstream/overlays/istio

# Jupyter Web App
- ../manifests-1.3-branch/apps/jupyter/notebook-controller/upstream/overlays/kubeflow

#Profiles + KFAM
- ../manifests-1.3-branch/apps/profiles/upstream/overlays/kubeflow

# Volumes Web App
- ../manifests-1.3-branch/apps/volumes-web-app/upstream/overlays/istio

# User namespace
- ../manifests-1.3-branch/common/user-namespace/base


# Katib
- ../manifests-1.3-branch/apps/katib/upstream/installs/katib-with-kubeflow
# Tensorboards Web App
-  ../manifests-1.3-branch/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
# Tensorboard Controller
-  ../manifests-1.3-branch/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio
# TFJob Operator
- ../manifests-1.3-branch/apps/tf-training/upstream/overlays/kubeflow
# Pytorch Operator
- ../manifests-1.3-branch/apps/pytorch-job/upstream/overlays/kubeflow
# MPI Operator
#- ../manifests-1.3-branch/apps/mpi-job/upstream/overlays/kubeflow
# MXNet Operator
#- ../manifests-1.3-branch/apps/mxnet-job/upstream/overlays/kubeflow
# XGBoost Operator
#- ../manifests-1.3-branch/apps/xgboost-job/upstream/overlays/kubeflow
