apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: noble
  region: us-west-2
  version: "1.19"

nodeGroups:
  - name: ng-1
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
    instancesDistribution:
      maxPrice: 1.0
      instanceTypes: ["m5.xlarge", "t3.xlarge"] 
      onDemandBaseCapacity: 3
      onDemandPercentageAboveBaseCapacity: 0
      spotInstancePools: 2
